### ISSUE TITLE
'NoneType' object has no attribute 'parent_work' in search results

### ISSUE THREAD

**Issue by tuskpot** [mouse-reeve/fedireads#134]
When I click on some search results, I get this error:

> AttributeError at /book/OL8088782W
> 'NoneType' object has no attribute 'parent_work'

I found this with a search for "titus groan". These result URLs gave me the error:
http://fedireads-test.glitch.me/book/OL8088782W
http://fedireads-test.glitch.me/book/OL10473260W
http://fedireads-test.glitch.me/book/OL2917010W

These results worked correctly:
http://fedireads-test.glitch.me/book/OL7920216W
http://fedireads-test.glitch.me/book/OL7920207W

Here's the extended error message:

```
Environment:


Request Method: GET
Request URL: http://fedireads-test.glitch.me/book/OL8088782W

Django Version: 3.0.3
Python Version: 3.7.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'fedireads',
 'celery']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/app/.local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/app/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/fedireads/views.py", line 356, in book_page
    work = book.parent_work

Exception Type: AttributeError at /book/OL8088782W
Exception Value: 'NoneType' object has no attribute 'parent_work'



```

**Comment by mouse-reeve** [comment]
thank you, yes! I have refactored the openlibrary connector which I *think* solves this issue. I'll deploy it to the demo site

**Comment by mouse-reeve** [comment]
should be working now

**Comment by tuskpot** [comment]
Confirmed. Thank you for the quick fix!
